// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	CONTRACT_QUEUE: Queue;
	ORBITER_PRIVATE_KEY: string;
	BASE_ALCHEMY_URL: string;
	CONTRACT_ADDRESS: string;
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	SITE_CONTRACT: KVNamespace;
}
